hyperparameters:
  actor_lr: 0.0005
  critic_lr: 0.003
  actor_hidden_dim: 256
  critic_hidden_dim: 256
  avg_game_length: 38 # found from random testing, will change with more players
  # capacity and batch size expressed in # of games (multiplied with avg_game_length)
  mem_capacity: 50
  mem_batch_size: 10
  eps_clip: 0.1
  entropy_coeff: 0.01
  gamma: 0.99

game_info:
  num_players: 2
